# Generated by Django 4.1 on 2022-08-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManejoNotas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nombre',
            field=models.TextField(),
        ),
    ]
