# Generated by Django 4.1 on 2022-08-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManejoNotas', '0003_alter_nota_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nota',
            name='texto',
            field=models.TextField(),
        ),
    ]
